---
parameters:
  - name: pnpmCommands
    type: object
    default: []
  - name: terraformVersion
    type: string
    # renovate: depName=terraform
    default: 1.12.1
  - name: useDotNet
    type: boolean
    default: false
  - name: usePnpm
    type: boolean
    default: false
  - name: pnpmVersion
    type: string
    default: ^10
  - name: usePnpmCache
    type: boolean
    default: true
  - name: usePipCache
    type: boolean
    default: true
  - name: useTerraform
    type: boolean
    default: false
  - name: skipRefs
    type: object
    default:
      - refs/heads/main
  - name: nodeVersion
    type: string
    default: 24.x
  - name: vmImage
    type: string
    default: ubuntu-latest

jobs:
  - job: ValidatePreCommit
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: Validate Pre-Commit
    pool:
      # Hardcoded to avoid consuming an expensive agent for a simple check
      vmImage: ubuntu-latest
    steps:
      - checkout: none
      - bash: |
          for ref in ${{ join(' ', parameters.skipRefs) }}; do
            if [[ "$(Build.SourceBranch)" == "$ref" ]]; then
              echo "Primary branch $ref — skipping pre-commit"
              exit 0
            fi
          done
          MSG="Pre-commit requires a PR build."
          MSG+=" Manually running a PR branch does"
          MSG+=" not set the PR variables needed by"
          MSG+=" this job. Comment \`/azp run\` on"
          MSG+=" the PR or target a primary branch."
          echo "##vso[task.logissue type=error]$MSG"
          exit 1
        displayName: Validate Branch
  - job: RunPreCommit
    condition: eq(variables['Build.Reason'], 'PullRequest')
    displayName: Run Pre-Commit
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - checkout: self
        persistCredentials: true
      # This is necessary to do a diff between the PR and the target branch
      - script: git fetch --no-tags --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        displayName: Fetch Branches
      - task: UseNode@1
        displayName: Use Node ${{ parameters.nodeVersion }}
        inputs:
          version: ${{ parameters.nodeVersion }}
      - ${{ if eq(parameters.useDotNet, true) }}:
          - task: NuGetAuthenticate@1
            displayName: Authenticate NuGet Internal
          - script: dotnet tool restore
            displayName: Install .NET Tools
      - ${{ if eq(parameters.usePnpm, true) }}:
          - template: pnpm-tasks.yml
            parameters:
              version: ${{ parameters.pnpmVersion }}
              useCache: ${{ parameters.usePnpmCache }}
          # pre-commit stashes unstaged changes, so we need to stage .npmrc so it can authenticate
          - script: git add .npmrc
            displayName: Stage .npmrc
          - ${{ each command in parameters.pnpmCommands }}:
              - script: pnpm ${{ command }}
                displayName: pnpm ${{ command }}
      - ${{ if eq(parameters.useTerraform, true) }}:
          # Terraform is no longer installed by default on the ubuntu-latest image
          # https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks
          - task: TerraformInstaller@1
            displayName: Install Terraform ${{ parameters.terraformVersion }}
            inputs:
              terraformVersion: ${{ parameters.terraformVersion }}
          - script: |
              INSTALL_URL="\
                https://raw.githubusercontent.com/terraform-linters/tflint/v0.58.0/install_linux.sh"
              curl -s $INSTALL_URL | bash
            displayName: Install TFLint
      - template: pip-tasks.yml
        parameters:
          useCache: ${{ parameters.usePipCache }}
      # Adapted from pre-commit docs:
      # https://pre-commit.com/index.html#azure-pipelines-example
      - task: Cache@2
        displayName: Restore Pre-Commit Cache
        inputs:
          key: pre-commit | .pre-commit-config.yaml | "$(PythonVersion)"
          path: $(PRE_COMMIT_HOME)
      - script: |
          pre-commit run \
            --color=always \
            --show-diff-on-failure \
            --verbose \
            --from-ref=origin/$(System.PullRequest.targetBranchName) \
            --to-ref=$(System.PullRequest.SourceCommitId)
        displayName: Run Pre-Commit Checks
    variables:
      # Enable pre-commit to access private npm feed
      # https://github.com/pre-commit/pre-commit/issues/1452#issuecomment-2209253779
      - name: NPM_CONFIG_GLOBALCONFIG
        value: $(Build.SourcesDirectory)/.npmrc
      - name: PRE_COMMIT_HOME
        value: $(Pipeline.Workspace)/pre-commit-cache
